-- =============================================================================
-- Immigram — Seed Visa Programs for 10 Countries
-- =============================================================================

-- ---------------------------------------------------------------------------
-- United States
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('US', 'United States', 'work', 'H-1B Specialty Occupation', 'H-1B', 'For workers in specialty occupations requiring a bachelor''s degree or higher.', 'Requires a job offer from a US employer, bachelor''s degree or equivalent in the specialty field, and the employer must file a petition.', 90, 270, 2500, ARRAY['Passport', 'Degree certificates', 'Resume/CV', 'Job offer letter', 'Labor Condition Application']),
('US', 'United States', 'work', 'L-1 Intracompany Transfer', 'L-1', 'For employees transferring within the same company to a US office.', 'Must have worked for the company abroad for at least 1 year in the past 3 years in a managerial, executive, or specialized knowledge capacity.', 30, 180, 2000, ARRAY['Passport', 'Employment verification', 'Company documentation', 'Petition form I-129']),
('US', 'United States', 'work', 'O-1 Extraordinary Ability', 'O-1', 'For individuals with extraordinary ability in sciences, arts, education, business, or athletics.', 'Must demonstrate extraordinary ability through sustained national or international acclaim, with extensive documentation.', 30, 120, 3000, ARRAY['Passport', 'Evidence of extraordinary ability', 'Letters of recommendation', 'Awards documentation']),
('US', 'United States', 'work', 'EB-2 National Interest Waiver', 'EB-2 NIW', 'Green card for professionals with advanced degrees whose work benefits the US national interest.', 'Advanced degree or exceptional ability, proposed endeavor has substantial merit and national importance.', 365, 730, 4000, ARRAY['Passport', 'Advanced degree', 'Evidence of national interest', 'Letters of support']),
('US', 'United States', 'study', 'F-1 Student Visa', 'F-1', 'For full-time students enrolled at accredited US institutions.', 'Acceptance at SEVP-certified school, proof of financial support, ties to home country.', 30, 90, 350, ARRAY['Passport', 'I-20 form', 'Financial documents', 'Academic transcripts', 'SEVIS fee receipt']),
('US', 'United States', 'permanent_residence', 'EB-1A Extraordinary Ability Green Card', 'EB-1A', 'Permanent residence for those with extraordinary ability.', 'Must meet 3 of 10 criteria demonstrating extraordinary ability, no job offer required.', 365, 1095, 5000, ARRAY['Passport', 'Evidence of extraordinary ability', 'Form I-140', 'Form I-485']),
('US', 'United States', 'family', 'CR-1/IR-1 Spouse Visa', 'CR-1/IR-1', 'For spouses of US citizens.', 'Must be legally married to a US citizen. CR-1 for marriages under 2 years, IR-1 for marriages over 2 years.', 365, 730, 1200, ARRAY['Passport', 'Marriage certificate', 'Proof of relationship', 'Financial sponsorship']),
('US', 'United States', 'investment', 'EB-5 Investor Visa', 'EB-5', 'Green card through investment in a US business.', 'Minimum investment of $800,000 in a targeted employment area or $1,050,000 elsewhere, creating 10 full-time jobs.', 730, 1825, 10000, ARRAY['Passport', 'Proof of investment', 'Business plan', 'Source of funds documentation']);

-- ---------------------------------------------------------------------------
-- United Kingdom
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('GB', 'United Kingdom', 'work', 'Skilled Worker Visa', 'Skilled Worker', 'For workers with a job offer from a licensed UK sponsor.', 'Job offer from licensed sponsor, meets skill level (RQF 3+), meets salary threshold (generally £26,200+), English language requirement.', 21, 56, 1500, ARRAY['Passport', 'Certificate of Sponsorship', 'English language proof', 'Financial evidence']),
('GB', 'United Kingdom', 'work', 'Global Talent Visa', 'Global Talent', 'For leaders or potential leaders in academia, research, arts, or digital technology.', 'Endorsement from a recognized UK body, exceptional talent or exceptional promise.', 14, 56, 800, ARRAY['Passport', 'Endorsement evidence', 'CV', 'Letters of recommendation']),
('GB', 'United Kingdom', 'study', 'Student Visa', 'Student', 'For students accepted at a licensed UK education provider.', 'Confirmation of acceptance (CAS), proof of financial support, English language requirement.', 21, 42, 500, ARRAY['Passport', 'CAS reference', 'Financial documents', 'English language proof', 'Academic qualifications']),
('GB', 'United Kingdom', 'work', 'Innovator Founder Visa', 'Innovator Founder', 'For experienced business people seeking to establish an innovative business in the UK.', 'Endorsement from an approved body, innovative and viable business plan, scalable business idea.', 21, 56, 1500, ARRAY['Passport', 'Business plan', 'Endorsement letter', 'Financial evidence']),
('GB', 'United Kingdom', 'family', 'Family Visa (Spouse)', 'Family', 'For partners/spouses of British citizens or settled persons.', 'Genuine relationship, meet financial requirement (£29,000+), English language requirement.', 60, 180, 2000, ARRAY['Passport', 'Marriage certificate', 'Financial evidence', 'English language proof', 'Accommodation evidence']);

-- ---------------------------------------------------------------------------
-- Canada
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('CA', 'Canada', 'permanent_residence', 'Express Entry - Federal Skilled Worker', 'FSW', 'Points-based immigration for skilled workers.', 'Minimum 1 year skilled work experience, language proficiency (CLB 7+), education credential assessment, meet CRS score cutoff.', 180, 365, 1500, ARRAY['Passport', 'Language test results', 'Education credential assessment', 'Work reference letters', 'Police certificates']),
('CA', 'Canada', 'permanent_residence', 'Express Entry - Canadian Experience Class', 'CEC', 'For workers with Canadian work experience.', 'Minimum 1 year of skilled work experience in Canada within last 3 years, language proficiency.', 180, 365, 1500, ARRAY['Passport', 'Language test results', 'Canadian work experience proof', 'Police certificates']),
('CA', 'Canada', 'permanent_residence', 'Provincial Nominee Program', 'PNP', 'Provincial nomination for permanent residence.', 'Meet the specific requirements of a Canadian province/territory, receive a nomination, then apply for PR.', 270, 540, 2000, ARRAY['Passport', 'Provincial nomination certificate', 'Language test', 'Education documents', 'Work experience proof']),
('CA', 'Canada', 'work', 'Temporary Work Permit', 'LMIA Work Permit', 'Employer-specific work permit requiring LMIA.', 'Job offer from Canadian employer with approved LMIA, meet job qualifications.', 30, 120, 300, ARRAY['Passport', 'Job offer letter', 'LMIA approval', 'Qualifications proof']),
('CA', 'Canada', 'study', 'Study Permit', 'Study Permit', 'For international students at designated learning institutions.', 'Acceptance at DLI, proof of financial support, no criminal record, good health.', 30, 120, 150, ARRAY['Passport', 'Letter of acceptance', 'Financial proof', 'Language test results']);

-- ---------------------------------------------------------------------------
-- Australia
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('AU', 'Australia', 'permanent_residence', 'Skilled Independent Visa', '189', 'Points-based permanent residence without employer or state sponsorship.', 'Occupation on skilled occupation list, skills assessment, minimum 65 points, English proficiency, under 45 years.', 180, 730, 3000, ARRAY['Passport', 'Skills assessment', 'English test results', 'Work references', 'Police checks', 'Health examination']),
('AU', 'Australia', 'permanent_residence', 'Skilled Nominated Visa', '190', 'State/territory nominated permanent residence.', 'State nomination, occupation on state list, skills assessment, minimum 65 points including 5 for nomination.', 180, 540, 3000, ARRAY['Passport', 'State nomination', 'Skills assessment', 'English test', 'Work references']),
('AU', 'Australia', 'work', 'Employer Nomination Scheme', '186', 'Employer-sponsored permanent residence.', 'Nomination by Australian employer, relevant skills and qualifications, at least 3 years work experience, English proficiency.', 180, 365, 3000, ARRAY['Passport', 'Employer nomination', 'Skills assessment', 'English test', 'Work experience proof']),
('AU', 'Australia', 'study', 'Student Visa', '500', 'For international students studying in Australia.', 'Enrolled in registered course, genuine temporary entrant, financial capacity, English proficiency, health insurance.', 14, 90, 500, ARRAY['Passport', 'Confirmation of Enrolment', 'Financial evidence', 'English test', 'Health insurance']),
('AU', 'Australia', 'work', 'Temporary Skill Shortage Visa', '482', 'Employer-sponsored temporary work visa.', 'Sponsored by approved employer, occupation on skills list, relevant skills and experience, English proficiency.', 30, 120, 2000, ARRAY['Passport', 'Sponsor nomination', 'Skills assessment', 'English test', 'Work experience proof']);

-- ---------------------------------------------------------------------------
-- Germany
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('DE', 'Germany', 'work', 'EU Blue Card', 'Blue Card', 'For highly qualified workers with a university degree.', 'University degree, job offer with minimum salary (€45,300 or €41,042 for shortage occupations), relevant qualifications.', 30, 90, 150, ARRAY['Passport', 'University degree', 'Job contract', 'CV', 'Health insurance proof']),
('DE', 'Germany', 'work', 'Skilled Worker Visa', 'Fachkräftevisum', 'For qualified professionals with vocational training.', 'Recognized qualification, job offer or job-seeking visa, German language skills may be required.', 30, 120, 150, ARRAY['Passport', 'Qualification recognition', 'Job contract', 'CV', 'Language certificate']),
('DE', 'Germany', 'work', 'Job Seeker Visa', 'Job Seeker', 'For qualified professionals looking for work in Germany.', 'University degree, financial means for 6-month stay, no work allowed on this visa.', 14, 60, 100, ARRAY['Passport', 'University degree', 'CV', 'Financial proof', 'Health insurance']),
('DE', 'Germany', 'study', 'Student Visa', 'Student', 'For international students at German universities.', 'University admission, proof of financial resources (€11,208/year), health insurance.', 30, 90, 100, ARRAY['Passport', 'University admission letter', 'Financial proof', 'Health insurance', 'Academic transcripts']),
('DE', 'Germany', 'permanent_residence', 'Settlement Permit', 'Niederlassungserlaubnis', 'Permanent residence after 21-33 months with Blue Card.', 'Blue Card holder for 21-33 months, German language skills, pension contributions, no criminal record.', 30, 90, 200, ARRAY['Passport', 'Blue Card', 'German language certificate', 'Pension proof', 'Employment contract']);

-- ---------------------------------------------------------------------------
-- Netherlands
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('NL', 'Netherlands', 'work', 'Highly Skilled Migrant', 'Kennismigrant', 'For highly skilled workers with above-average salary.', 'Job offer from recognized sponsor, meet minimum salary requirement (age-dependent), relevant qualifications.', 14, 60, 400, ARRAY['Passport', 'Employment contract', 'Degree certificates', 'CV']),
('NL', 'Netherlands', 'work', 'Orientation Year Permit', 'Zoekjaar', 'For recent graduates to seek employment in the Netherlands.', 'Graduated from Dutch institution or top-200 international university within 3 years, sufficient funds.', 14, 60, 250, ARRAY['Passport', 'Degree certificate', 'Financial proof']),
('NL', 'Netherlands', 'work', 'Self-Employment Visa', 'Self-Employment', 'For entrepreneurs starting a business in the Netherlands.', 'Viable business plan, sufficient financial resources, adds value to Dutch economy (points-based assessment).', 60, 120, 500, ARRAY['Passport', 'Business plan', 'Financial proof', 'CV', 'Diploma']),
('NL', 'Netherlands', 'study', 'Student Visa', 'Student', 'For students at Dutch educational institutions.', 'Admitted to accredited institution, sufficient financial means, health insurance.', 14, 60, 250, ARRAY['Passport', 'Enrollment letter', 'Financial proof', 'Health insurance']);

-- ---------------------------------------------------------------------------
-- France
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('FR', 'France', 'work', 'Talent Passport', 'Passeport Talent', 'Multi-year residence permit for skilled workers, entrepreneurs, investors, and researchers.', 'Varies by category: qualified employees (salary 2x minimum), researchers, entrepreneurs, investors, artists.', 30, 90, 300, ARRAY['Passport', 'Employment contract or project docs', 'Degree certificates', 'Financial proof']),
('FR', 'France', 'work', 'Employee Work Visa', 'Salarié', 'Standard work visa for employment in France.', 'Job offer from French employer, employer obtains work authorization, relevant qualifications.', 30, 120, 200, ARRAY['Passport', 'Work contract', 'Work authorization', 'Qualifications proof']),
('FR', 'France', 'study', 'Student Visa (VLS-TS)', 'VLS-TS Étudiant', 'Long-stay student visa validated as residence permit.', 'Accepted at French educational institution, Campus France validation, sufficient financial means.', 14, 60, 100, ARRAY['Passport', 'Acceptance letter', 'Campus France attestation', 'Financial proof', 'Health insurance']),
('FR', 'France', 'family', 'Family Reunification', 'Regroupement Familial', 'For family members of residents in France.', 'Sponsor must have resided in France for 18+ months, adequate housing and income.', 90, 365, 300, ARRAY['Passport', 'Family relationship proof', 'Sponsor''s residence permit', 'Housing proof', 'Income proof']);

-- ---------------------------------------------------------------------------
-- Sweden
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('SE', 'Sweden', 'work', 'Work Permit', 'Arbetstillstånd', 'For workers with a job offer from a Swedish employer.', 'Job offer meeting minimum salary and conditions, terms comparable to Swedish collective agreements, employer advertised position in EU.', 30, 180, 250, ARRAY['Passport', 'Job offer', 'Employment terms', 'Union statement', 'Health insurance']),
('SE', 'Sweden', 'work', 'EU Blue Card (Sweden)', 'Blue Card SE', 'For highly qualified workers meeting EU Blue Card criteria.', 'Higher education degree, job offer with salary at least 1.5x average Swedish salary.', 30, 120, 250, ARRAY['Passport', 'Degree certificate', 'Employment contract', 'Salary documentation']),
('SE', 'Sweden', 'study', 'Residence Permit for Studies', 'Student', 'For non-EU students at Swedish universities.', 'Accepted at Swedish university, sufficient funds (SEK 9,450/month), comprehensive health insurance.', 30, 90, 150, ARRAY['Passport', 'University acceptance', 'Financial proof', 'Health insurance']),
('SE', 'Sweden', 'permanent_residence', 'Permanent Residence', 'PUT', 'After 4 years of legal residence with work permit.', '4 years of continuous residence, current employment, can support yourself.', 90, 365, 200, ARRAY['Passport', 'Residence history', 'Employment proof', 'Tax records']);

-- ---------------------------------------------------------------------------
-- New Zealand
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('NZ', 'New Zealand', 'permanent_residence', 'Skilled Migrant Category', 'SMC', 'Points-based residence visa for skilled workers.', 'Expression of Interest with 160+ points, skilled employment or offer, age under 56, health and character requirements.', 180, 365, 2000, ARRAY['Passport', 'Skills assessment', 'Job offer or employment proof', 'English test', 'Police certificates', 'Medical examination']),
('NZ', 'New Zealand', 'work', 'Accredited Employer Work Visa', 'AEWV', 'For workers with a job offer from an accredited NZ employer.', 'Job offer from accredited employer, meet skill and pay requirements, health and character checks.', 30, 90, 500, ARRAY['Passport', 'Job offer', 'Employer accreditation proof', 'Qualifications', 'Police certificates']),
('NZ', 'New Zealand', 'study', 'Student Visa', 'Student', 'For international students at NZ education providers.', 'Offer of place, sufficient funds (NZ$20,000/year), return travel, health insurance.', 14, 60, 250, ARRAY['Passport', 'Offer of place', 'Financial proof', 'Health insurance']),
('NZ', 'New Zealand', 'work', 'Working Holiday Visa', 'Working Holiday', 'For young people (18-30/35) to travel and work in NZ.', 'Age 18-30 (or 35 for some countries), sufficient funds, return ticket or funds for one.', 7, 30, 200, ARRAY['Passport', 'Financial proof', 'Return ticket proof', 'Health insurance']);

-- ---------------------------------------------------------------------------
-- Ireland
-- ---------------------------------------------------------------------------
INSERT INTO imm_visa_programs (country_code, country_name, visa_type, program_name, program_code, description, eligibility_summary, processing_time_days_min, processing_time_days_max, cost_estimate_usd, documents_required) VALUES
('IE', 'Ireland', 'work', 'Critical Skills Employment Permit', 'CSEP', 'For highly skilled workers in shortage occupations.', 'Job offer in eligible occupation, minimum salary €38,000 (or €64,000 for non-critical list), degree-level qualification.', 14, 60, 1200, ARRAY['Passport', 'Job offer/contract', 'Degree certificates', 'CV', 'Employer registration']),
('IE', 'Ireland', 'work', 'General Employment Permit', 'GEP', 'Standard work permit for employment in Ireland.', 'Job offer with minimum salary €34,000, labor market needs test, occupation not on ineligible list.', 14, 90, 1200, ARRAY['Passport', 'Job offer', 'Qualifications', 'Labour market needs test evidence']),
('IE', 'Ireland', 'work', 'Startup Entrepreneur Programme', 'STEP', 'For entrepreneurs with innovative business ideas.', 'Innovative business idea, €50,000 funding, endorsed by Enterprise Ireland or approved body.', 30, 120, 500, ARRAY['Passport', 'Business plan', 'Funding proof', 'Endorsement letter']),
('IE', 'Ireland', 'study', 'Student Visa (Stamp 2)', 'Stamp 2', 'For non-EEA students studying in Ireland.', 'Enrolled at recognized institution, fees paid, sufficient funds (€10,000), health insurance.', 14, 60, 150, ARRAY['Passport', 'Enrollment letter', 'Fees receipt', 'Financial proof', 'Health insurance']);
